### ISSUE TITLE
Keep the user naming sceme close to defaults

### ISSUE THREAD

**Issue by Grothesk242** [buanet/ioBroker.raspberry-os#1]
Please do not rename uid 1000 to user 'iobroker' but leave it with the default naming of 'pi'. 
There may be situations (especially when running with a Desktop Environment (bad idea anyway)) where the existence of such a user is assumed and you run into awkward situations. 

If you want to introduce a iobroker specific user please name it something like 'iobadmin' with uid 1002/gid 1002.

**Comment by buanet** [comment]
In v1.1.0 the default user is now "pi" and can be used to administer the iobroker installation.
The user "iobroker" is now only a service user. Login with "iobroker" is no longer possible by default. 

Attention: The Image is based on Raspbian OS lite image and not made for running any desktop environment.
If a ui is needed i would prefer using an official Raspberry OS Image and manually install iobroker to this image.  

I'll close this issue now.
