### ISSUE TITLE
Adding the images to rpi-imager

### ISSUE THREAD

**Issue by tim2zg** [buanet/ioBroker.raspberry-os#10]
Hey,
I saw today that the rpi-imager tool features other home automation images in their one-click installer like openHAB, maybe it is possible to add ioBroker to the repo. 
Best regards,
Tim

**Comment by buanet** [comment]
Hi, the request is open for more than a year now. Feel free to support us here: https://github.com/raspberrypi/rpi-imager/issues/375

I posted a workaround here:
https://docs.buanet.de/iobroker-raspberrypios-image/docs/

Regards,
André

**Comment by buanet** [comment]
We will go for another try with upcoming rpi image version v2. I'll close this issue.
