### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by drsnuggles1982** [buanet/ioBroker.raspberry-os#12]
Was there any update on username and password for ssh connection. I use pi as user and raspberry as password.

Yes I checked if y is really a y and not a z.

Always is the feedback access denied

**Comment by buanet** [comment]
nope, no change.

**Comment by drsnuggles1982** [comment]
Strange!
Any ideas why this could happen? ![image](https://github.com/buanet/ioBroker.raspberry-os/assets/45869908/fd098237-8967-4fe2-b3df-783d69d13b14)

**Comment by buanet** [comment]
Did you test console login? Maybe the user is not allowed to log on via ssh by default, like the error message says?

**Comment by drsnuggles1982** [comment]
> Did you test console login? Maybe the user is not allowed to log on via ssh by default, like the error message says?  

Not yet. I don't have an display available for my raspberry

**Comment by buanet** [comment]
I'm pretty sure you have to setup your own user at the console session. Another option is, to set the user when burning the image to your sd card with raspberry pi imager tool. I'll close this issue.

**Comment by drsnuggles1982** [comment]
Correct! I had to connect directly a screen and a keyboard and have to set user and password
