### ISSUE TITLE
System falls asleep again and again

### ISSUE THREAD

**Issue by hennott** [buanet/ioBroker.raspberry-os#3]
I have taken the image unchanged and run it on an RPi3B. However, the system keeps falling asleep. After a few hours, it is not accessible. Only this image has this issue, my other Raspberry OS do not have this. The system is connected via eth0, which eliminates the WLAN power manager as a source for this problem. The RPi LED is no longer lit, but the network LED is still lit.

**Comment by buanet** [comment]
Hi, can anybody else confirm this behavior?
I have no RPi3B Hardware to test this.
Only can say, that it is running without interuption on my RPi4. 

@hennott Are there any other things you say about this issue? Did you test accessing the "frozen" pi on the console? 

Regards,
André

**Comment by hennott** [comment]
Hi .. the RPi4 is up and running and has a continous connection to the network. But the ioBroker over port 8081 or the bis with port 8082 aren´t avaiable and all the scripts stop working after a unspecific period of time.

I checked "service iobroker status" and it is up an running. And a restart with a few minutes bring the system up to live.

I´m using the v1.0.0 because I don´t know how to update to the newest version.

**Comment by buanet** [comment]
I now tested on RPi 4 and RPi 2B. They both running for more than a week now. So I'm not able to reproduce your issue so far.
As it seems ioBroker is going to stop working in your case, did you check de default iobroker log? maybe we can get some more information from there. another way could be checking the raspberry system logs.

Updating the raspberry pi image with a new one is not necessary. For updating the linux base system, running "apt-get update" and "apt-get upgrade" will do this.

Regards,
 André

**Comment by buanet** [comment]
No response for 3 weeks now.
I'll close this issue.
Feel free to reopen if needed. 

Regards,
André
